---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    container_name: kafka
    image: bitnami/kafka:3.0.0
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui
    ports:
      - "10.0.11.1:8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    restart: always
    depends_on:
      - kafka

  mongo1:
    image: mongo
    ports:
      - "10.0.11.1:27017:27017"
    restart: always
    volumes:
      - mongodb_data_1:/data/db
    command: mongod --replSet dev-mongo-set --bind_ip_all
  mongo2:
    image: mongo
    ports:
      - "10.0.11.1:27018:27017"
    restart: always
    volumes:
      - mongodb_data_2:/data/db
    command: mongod --replSet dev-mongo-set --bind_ip_all
  mongo3:
    image: mongo
    ports:
      - "10.0.11.1:27019:27017"
    restart: always
    volumes:
      - mongodb_data_3:/data/db
    command: mongod --replSet dev-mongo-set --bind_ip_all

  mongoinit:
    image: mongo
    # this container will exit after executing the command
    restart: "no"
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    command: >
      mongosh --host mongo1:27017 --eval 
      '
      db = (new Mongo("mongo1:27017")).getDB("test");
      config = {
      "_id" : "dev-mongo-set",
      "members" : [
        {
          "_id" : 0,
          "priority": 1,
          "host" : "mongo1:27017"
        },
        {
          "_id" : 1,
          "priority": 0.5,
          "host" : "mongo2:27017"
        },
        {
          "_id" : 2,
          "priority": 0.5,
          "host" : "mongo3:27017"
        }
      ]
      };
      rs.initiate(config);
      '
  postgres:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - "10.0.11.1:5432:5432"
    restart: always

  redis:
    image: redis:7-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/data
    ports:
      - 10.0.11.1:6379:6379
    restart: always

  api:
    image: allokanic/api
    depends_on:
      - mongoinit
      - kafka
      - redis
      - postgres
    ports:
      - 80:8080
    env_file:
      - secrets_profile.yaml
    restart: always

  tg-bot:
    image: allokanic/tg-bot
    depends_on:
      - mongoinit
      - kafka
      - kafka-ui
      - redis
      - postgres
    env_file:
      - secrets_profile.yaml
    restart: always

volumes:
  postgres_volume:
  mongodb_data_1:
  mongodb_data_2:
  mongodb_data_3:
  redis_data:
